"""Tests for the AGENTS.md / CLAUDE.md compatible export (Task 6).

Focus: the export must NEVER leak staging, sensitive, or project-scoped
knowledge into a global export, and must emit summary/metadata only.
"""

from __future__ import annotations

from piia_engram import agents_md_export as A


def _lesson(summary, *, tier="verified", status="active", sensitivity=None,
            domain="", project=None):
    e = {"summary": summary, "tier": tier, "status": status, "domain": domain}
    if sensitivity is not None:
        e["sensitivity"] = sensitivity
    if project is not None:
        e["project"] = project
    return e


def _decision(question, choice, *, tier="verified", status="active", project=None):
    e = {"question": question, "choice": choice, "tier": tier, "status": status}
    if project is not None:
        e["project"] = project
    return e


# --- selection rules -------------------------------------------------------

def test_excludes_staging():
    sel = A.select_exportable([_lesson("staged", tier="staging")])
    assert sel == []


def test_excludes_non_active():
    sel = A.select_exportable([_lesson("old", status="outdated")])
    assert sel == []


def test_fail_closed_when_tier_missing():
    # An entry with NO tier key must not be exported (fail closed, not default-verified).
    sel = A.select_exportable([{"summary": "no tier key here at all", "status": "active"}])
    assert sel == []


def test_excludes_sensitive_and_private():
    items = [
        _lesson("public ok", sensitivity="public"),
        _lesson("work ok", sensitivity="work"),
        _lesson("private hidden", sensitivity="private"),
        _lesson("secret hidden", sensitivity="secret"),
    ]
    sel = A.select_exportable(items)
    summaries = {s["summary"] for s in sel}
    assert summaries == {"public ok", "work ok"}


def test_value_floor_excludes_credential_content():
    # A benign label but the content carries a credential shape -> classified secret.
    leaky = _lesson("api key is sk-proj-ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")
    sel = A.select_exportable([leaky])
    assert sel == []


def test_global_scope_excludes_project_entries():
    items = [
        _lesson("generalizable"),
        _lesson("proj specific", project="engram"),
    ]
    sel = A.select_exportable(items, scope="global")
    assert [s["summary"] for s in sel] == ["generalizable"]


def test_project_scope_includes_only_that_project():
    items = [
        _lesson("global one"),
        _lesson("engram one", project="engram"),
        _lesson("other one", project="reader"),
    ]
    sel = A.select_exportable(items, scope="project", project="engram")
    assert [s["summary"] for s in sel] == ["engram one"]


# --- rendering -------------------------------------------------------------

def test_build_renders_decisions_and_lessons():
    md = A.build_agents_md_export(
        lessons=[_lesson("always pin deps", domain="python")],
        decisions=[_decision("which db", "sqlite for local-first")],
        scope="global",
    )
    assert "## Engram — durable knowledge (global)" in md
    assert "### Key decisions" in md
    assert "which db" in md and "sqlite for local-first" in md
    assert "### Lessons" in md
    assert "always pin deps" in md
    assert "domain: python" in md


def test_build_excludes_sensitive_from_output():
    md = A.build_agents_md_export(
        lessons=[
            _lesson("safe lesson", sensitivity="work"),
            _lesson("private lesson", sensitivity="private"),
        ],
    )
    assert "safe lesson" in md
    assert "private lesson" not in md


def test_build_emits_metadata_only_no_internal_fields():
    leaky = _lesson("visible summary", domain="x")
    leaky.update({"id": "deadbeef1234", "access_count": 99, "risk_flags": ["mcp_config"]})
    md = A.build_agents_md_export(lessons=[leaky])
    assert "visible summary" in md
    assert "deadbeef1234" not in md
    assert "access_count" not in md
    assert "risk_flags" not in md


def test_build_empty_when_nothing_qualifies():
    md = A.build_agents_md_export(lessons=[_lesson("staged", tier="staging")])
    assert "No verified, non-sensitive knowledge" in md


def test_build_has_provenance_comment_banner():
    md = A.build_agents_md_export(lessons=[_lesson("x")])
    assert "Generated by Engram" in md
    assert "Staging and sensitive content are excluded" in md
