"""Phase 2: the `engram export-agents-md` CLI entrypoint.

Validates that the CLI wiring honors the contract guarantees already unit-tested
on the helper (verified-only, no staging, no sensitive, summary-only) and that
``--out`` refuses to clobber an existing file.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from piia_engram import setup_wizard as sw
from piia_engram.core import Engram


@pytest.fixture()
def store(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    root = tmp_path / "engram"
    monkeypatch.setenv("ENGRAM_DIR", str(root))
    eng = Engram(root=root)
    # verified (default tier) + non-sensitive → exported
    eng.add_lesson({
        "summary": "Always pin dependency versions in CI",
        "domain": "ci",
        "tier": "verified",
        "status": "active",
    })
    eng.add_decision({"question": "ORM choice", "choice": "use SQLAlchemy"})
    # staging → excluded
    eng.add_lesson({"summary": "DRAFT idea about caching that is not yet vetted",
                    "domain": "perf", "tier": "staging"})
    # sensitive → excluded
    eng.add_lesson({"summary": "prod DB password is hunter2 do not share",
                    "domain": "secops", "sensitivity": "secret"})
    return root


class TestExportAgentsMdCli:
    def test_global_export_includes_verified_excludes_staging_and_secret(
        self, store: Path, capsys
    ):
        rc = sw._run_export_agents_md([])
        assert rc == 0
        out = capsys.readouterr().out
        assert "Always pin dependency versions in CI" in out
        assert "use SQLAlchemy" in out
        # staging + sensitive must NOT leak into a committable file
        assert "DRAFT idea about caching" not in out
        assert "hunter2" not in out
        # honest banner present
        assert "Generated by Engram" in out

    def test_invalid_scope_rejected(self, store: Path, capsys):
        rc = sw._run_export_agents_md(["--scope", "bogus"])
        assert rc == 2
        assert "must be" in capsys.readouterr().out

    def test_project_scope_requires_project(self, store: Path, capsys):
        rc = sw._run_export_agents_md(["--scope", "project"])
        assert rc == 2
        assert "requires --project" in capsys.readouterr().out

    def test_out_writes_file_and_refuses_overwrite(self, store: Path, tmp_path: Path, capsys):
        dest = tmp_path / "out" / "AGENTS_block.md"
        rc = sw._run_export_agents_md(["--out", str(dest)])
        assert rc == 0
        assert dest.is_file()
        body = dest.read_text(encoding="utf-8")
        assert "Always pin dependency versions in CI" in body
        capsys.readouterr()
        # second write must refuse (never clobber a hand-maintained file)
        rc2 = sw._run_export_agents_md(["--out", str(dest)])
        assert rc2 == 2
        assert "refusing to overwrite" in capsys.readouterr().out
