"""Watcher autostart install: ``engram watcher install|uninstall|status``.

Design constraints:

- **No elevation.** ``schtasks /SC ONLOGON`` requires admin rights on most
  Windows setups, so autostart uses the per-user Startup folder instead
  (``%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\Startup``). The
  shortcut is plainly named and user-deletable — transparent by design.
- **No console flash.** The shortcut targets ``pythonw.exe`` running a
  generated ``.pyw`` launcher, so nothing pops up at logon.
- **Self-contained launcher.** The launcher bakes in the package location
  and ``ENGRAM_DIR`` observed at install time, so it works for both pip
  installs and source checkouts without touching global environment vars.
- **Non-Windows**: prints cron/launchd guidance instead of writing anything.

Uninstall removes exactly the two artifacts install creates (shortcut +
launcher); it never touches watcher state or saved contexts.
"""

from __future__ import annotations

import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

_SHORTCUT_NAME = "Piia Engram Watcher.lnk"
_LAUNCHER_NAME = "watcher_launcher.pyw"
_DEFAULT_INTERVAL = 60.0


def engram_dir() -> Path:
    base = os.environ.get("ENGRAM_DIR", "").strip() or "~/.engram"
    return Path(base).expanduser()


def startup_dir() -> Path:
    """Per-user Startup folder (no admin rights needed to write)."""
    appdata = os.environ.get("APPDATA", "").strip()
    base = Path(appdata) if appdata else Path.home() / "AppData" / "Roaming"
    return base / "Microsoft" / "Windows" / "Start Menu" / "Programs" / "Startup"


def shortcut_path() -> Path:
    return startup_dir() / _SHORTCUT_NAME


def launcher_path() -> Path:
    return engram_dir() / _LAUNCHER_NAME


def _pythonw() -> Path:
    """Prefer the console-less interpreter next to the current one."""
    exe = Path(sys.executable)
    candidate = exe.with_name("pythonw.exe")
    return candidate if candidate.exists() else exe


def _package_src_root() -> Path:
    """Directory that must be on sys.path for ``import piia_engram``."""
    import piia_engram

    return Path(piia_engram.__file__).resolve().parent.parent


def build_launcher_source(interval: float = _DEFAULT_INTERVAL) -> str:
    """Generate the .pyw launcher with install-time paths baked in."""
    src_root = str(_package_src_root())
    data_dir = str(engram_dir())
    return (
        '"""Auto-generated by `engram watcher install`. Safe to delete."""\n'
        "import os\n"
        "import sys\n\n"
        f"os.environ.setdefault('ENGRAM_DIR', {data_dir!r})\n"
        f"_SRC = {src_root!r}\n"
        "if _SRC not in sys.path:\n"
        "    sys.path.insert(0, _SRC)\n\n"
        "from piia_engram.watcher.__main__ import main\n\n"
        f"sys.exit(main(['--interval', '{interval:g}']))\n"
    )


def _ps_quote(value: str) -> str:
    """Quote for a single-quoted PowerShell string literal."""
    return "'" + value.replace("'", "''") + "'"


def _create_shortcut(lnk: Path, target: Path, arguments: str, workdir: Path) -> None:
    """Create a .lnk via WScript.Shell (no admin, no extra deps)."""
    script = (
        "$s = (New-Object -ComObject WScript.Shell).CreateShortcut("
        + _ps_quote(str(lnk))
        + "); "
        + "$s.TargetPath = " + _ps_quote(str(target)) + "; "
        + "$s.Arguments = " + _ps_quote(arguments) + "; "
        + "$s.WorkingDirectory = " + _ps_quote(str(workdir)) + "; "
        + "$s.Description = 'Piia Engram session watcher (auto-saves AI tool "
        + "transcripts to local Engram contexts)'; "
        + "$s.Save()"
    )
    subprocess.run(
        ["powershell", "-NoProfile", "-NonInteractive", "-Command", script],
        check=True,
        capture_output=True,
        timeout=60,
    )


def install(interval: float = _DEFAULT_INTERVAL, *, start_now: bool = False) -> int:
    if sys.platform != "win32":
        _print_posix_guidance(interval)
        return 0

    launcher = launcher_path()
    launcher.parent.mkdir(parents=True, exist_ok=True)
    launcher.write_text(build_launcher_source(interval), encoding="utf-8")

    lnk = shortcut_path()
    lnk.parent.mkdir(parents=True, exist_ok=True)
    try:
        _create_shortcut(
            lnk,
            _pythonw(),
            f'"{launcher}"',
            engram_dir(),
        )
    except (subprocess.SubprocessError, OSError) as exc:
        print(f"[watcher] failed to create startup shortcut: {exc}")
        print(f"[watcher] launcher was written to: {launcher}")
        return 1

    print("[watcher] installed.")
    print(f"  launcher : {launcher}")
    print(f"  autostart: {lnk}")
    print(f"  interval : {interval:g}s (scan loop; saves debounced separately)")
    print("  remove with: engram watcher uninstall")

    if start_now:
        started = start_background()
        print("  started  : yes" if started else "  started  : FAILED (see above)")
    else:
        print("  not started yet — it will start at next logon,")
        print("  or run now: engram watcher start")
    return 0


def start_background() -> bool:
    """Spawn the launcher detached (same thing the logon shortcut does)."""
    launcher = launcher_path()
    if not launcher.exists():
        print("[watcher] launcher missing — run `engram watcher install` first")
        return False
    try:
        flags = 0
        if sys.platform == "win32":
            flags = subprocess.DETACHED_PROCESS | subprocess.CREATE_NEW_PROCESS_GROUP
        subprocess.Popen(
            [str(_pythonw()), str(launcher)],
            creationflags=flags,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            close_fds=True,
        )
        return True
    except OSError as exc:
        print(f"[watcher] failed to start: {exc}")
        return False


def uninstall() -> int:
    if sys.platform != "win32":
        print("[watcher] nothing installed by this tool on this platform.")
        return 0
    removed = []
    for path in (shortcut_path(), launcher_path()):
        try:
            if path.exists():
                path.unlink()
                removed.append(str(path))
        except OSError as exc:
            print(f"[watcher] could not remove {path}: {exc}")
            return 1
    if removed:
        print("[watcher] removed:")
        for item in removed:
            print(f"  {item}")
        print("[watcher] note: an already-running watcher keeps running until"
              " logoff; watcher state/logs are kept.")
    else:
        print("[watcher] nothing to remove (not installed).")
    return 0


def status() -> int:
    lnk = shortcut_path()
    launcher = launcher_path()
    state_file = engram_dir() / "logs" / "watcher_state.json"
    log_file = engram_dir() / "logs" / "watcher.log"

    print("[watcher] status")
    print(f"  autostart shortcut: {'yes' if lnk.exists() else 'no'} ({lnk})")
    print(f"  launcher          : {'yes' if launcher.exists() else 'no'} ({launcher})")
    if state_file.exists():
        stamp = datetime.fromtimestamp(state_file.stat().st_mtime)
        print(f"  last scan         : {stamp.isoformat(timespec='seconds')}")
    else:
        print("  last scan         : never (no state file yet)")
    if log_file.exists():
        try:
            lines = log_file.read_text(encoding="utf-8", errors="replace").splitlines()
            for line in lines[-3:]:
                print(f"  log| {line}")
        except OSError:
            pass
    return 0


def _print_posix_guidance(interval: float) -> None:
    print("[watcher] automatic install currently supports Windows only.")
    print("[watcher] manual setup — add one of the following:")
    print(f"  cron   : @reboot {sys.executable} -m piia_engram.watcher --interval {interval:g}")
    print("  systemd: a user service running the same command")
    print(f"  manual : {sys.executable} -m piia_engram.watcher --interval {interval:g}")


def run_watcher_cli(args: list[str]) -> int:
    """Subcommand router for ``engram watcher ...``."""
    usage = (
        "usage: engram watcher <command>\n"
        "  install [--interval N] [--start]  set up logon autostart (per-user, no admin)\n"
        "  start                             start the background watcher now\n"
        "  uninstall                         remove autostart + launcher\n"
        "  status                            show install/scan status\n"
        "  once                              run a single scan in the foreground\n"
    )
    if not args:
        print(usage)
        return 2
    cmd = args[0]
    if cmd == "install":
        interval = _DEFAULT_INTERVAL
        if "--interval" in args:
            try:
                interval = max(5.0, float(args[args.index("--interval") + 1]))
            except (IndexError, ValueError):
                print("invalid --interval value")
                return 2
        return install(interval, start_now="--start" in args)
    if cmd == "start":
        return 0 if start_background() else 1
    if cmd == "uninstall":
        return uninstall()
    if cmd == "status":
        return status()
    if cmd == "once":
        from .__main__ import main as watcher_main

        return watcher_main(["--once"])
    print(usage)
    return 2
